# Get all books 
GET http://localhost:3001/seafood HTTP/1.1
Content-Type: application/json

###

# Create a book
POST http://localhost:3001/seafood HTTP/1.1
Content-Type: application/json

{
    "productname": "Cá tra",
    "category": "Cá",
    "weight": 2000,
    "price": 140000,
    "stock": 200
}

###

# Update a book 
PUT http://localhost:3001/seafood/1 HTTP/1.1
Content-Type: application/json

{
    "productname": "Chân Cua Tuyết Trắng",
    "category": "Cua, Ghẹ, Tôm"
}

###

# Delete a book
DELETE http://localhost:3001/seafood/1 HTTP/1.1
Content-Type: application/json